      SUBROUTINE UMATINT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC,NNAME)
     5 BIND(C, NAME="UMATINT")
      USE ISO_C_BINDING
C      
      implicit real(8) (a-h,o-z)
C
      CHARACTER*80 MATERIALNAME
      CHARACTER(kind=C_CHAR), dimension(*), intent(in) :: CMNAME
      DOUBLE PRECISION, DIMENSION(NTENS,NTENS) :: DDSDDETR
      DOUBLE PRECISION, DIMENSION(3,3) :: DROTTR
      DOUBLE PRECISION, DIMENSION(3,3) :: DFGRD0TR
      DOUBLE PRECISION, DIMENSION(3,3) :: DFGRD1TR
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),
     2 DDSDDT(NTENS),DRPLDE(NTENS),
     3 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     4 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     5 JSTEP(4)
C
      MATERIALNAME = ''
      DO K1=1,NNAME
            MATERIALNAME = trim(MATERIALNAME)//trim(CMNAME(K1))
      END DO
C
      DO K1=1,NTENS
            DO K2=1,NTENS
                  DDSDDETR(K1,K2) = DDSDDE(K2,K1)
            END DO
      END DO
      DO K1=1,3
            DO K2=1,3
                  DROTTR(K1,K2) = DROT(K2,K1)
                  DFGRD0TR(K1,K2) = DFGRD0(K2,K1)
                  DFGRD1TR(K1,K2) = DFGRD1(K2,K1)
            END DO
      END DO
C
      CALL UMAT(STRESS,STATEV,DDSDDETR,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,MATERIALNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROTTR,PNEWDT,
     4 CELENT,DFGRD0TR,DFGRD1TR,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)
      END
C
C
      SUBROUTINE UMATINTTEST(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC,NNAME)
     5 BIND(C, NAME="UMATINTTEST")
      USE ISO_C_BINDING
C      
      implicit real(8) (a-h,o-z)
C
      CHARACTER*80 MATERIALNAME
      CHARACTER(kind=C_CHAR), dimension(*), intent(in) :: CMNAME
      DOUBLE PRECISION, DIMENSION(NTENS,NTENS) :: DDSDDETR
      DOUBLE PRECISION, DIMENSION(3,3) :: DROTTR
      DOUBLE PRECISION, DIMENSION(3,3) :: DFGRD0TR
      DOUBLE PRECISION, DIMENSION(3,3) :: DFGRD1TR
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),
     2 DDSDDT(NTENS),DRPLDE(NTENS),
     3 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     4 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     5 JSTEP(4)
C
      MATERIALNAME = ''
      DO K1=1,NNAME
            MATERIALNAME = trim(MATERIALNAME)//trim(CMNAME(K1))
      END DO
C     
      DO K1=1,NTENS
            DO K2=1,NTENS
                  DDSDDETR(K1,K2) = DDSDDE(K2,K1)
            END DO
      END DO
      DO K1=1,3
            DO K2=1,3
                  DROTTR(K1,K2) = DROT(K2,K1)
                  DFGRD0TR(K1,K2) = DFGRD0(K2,K1)
                  DFGRD1TR(K1,K2) = DFGRD1(K2,K1)
            END DO
      END DO
C
      CALL UMATTEST(STRESS,STATEV,DDSDDETR,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,MATERIALNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROTTR,PNEWDT,
     4 CELENT,DFGRD0TR,DFGRD1TR,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)
      DO K1=1,NTENS
            DO K2=1,NTENS
                  DDSDDE(K1,K2) = DDSDDETR(K2,K1)
            END DO
      END DO
      DO K1=1,3
            DO K2=1,3
                  DROT(K1,K2) = DROTTR(K2,K1)
                  DFGRD0(K1,K2) = DFGRD0TR(K2,K1)
                  DFGRD1(K1,K2) = DFGRD1TR(K2,K1)
            END DO
      END DO
      END